// src/lib/iconMap.js

import {
  AccountTree,
  Add,
  Analytics,
  Apps,
  Chat,
  CheckCircleOutline,
  ContentCopy,
  Favorite,
  Gavel,
  Group,
  Notifications,
  Remove,
  Settings,
  Storage,
  Warning,
  Facebook,
  Twitter,
  YouTube,
  Instagram,
  Public,
  Share,
  MoreVert,
} from "@mui/icons-material";

// A single mapping object for all icons
export const iconMap = {
  AccountTree: AccountTree,
  Add: Add,
  Analytics: Analytics,
  Apps: Apps,
  Chat: Chat,
  CheckCircleOutline: CheckCircleOutline,
  ContentCopy: ContentCopy,
  Database: Storage,
  Favorite: Favorite,
  Group: Gavel,
  Group: Group,
  MoreVert: MoreVert,
  Notifications: Notifications,
  Remove: Remove,
  Share: Share,
  Settings: Settings,
  Warning: Warning,

  facebook: Facebook,
  x: Twitter,
  instagram: Instagram,
  youtube: YouTube,
  truth_social: Public,
};
